POST http://localhost:5500/api/customers/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Kelly",
    "lastName": "Minoung",
    "email": "Minoung@gmail.com",
    "password": "gvtybun7u8io",
    "gender": "male",
    "birthday": "1974-03-25"
}