POST http://localhost:5500/api/customers/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Garry",
    "lastName": "Folkin",
    "email": "Folkin@gmail.com",
    "password": "67gga",
    "gender": "male",
    "birthday": "1976-10-15"
}